### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by kdoteu** [Kronos666/rkon-core#1]
Whats about a licence? 
I would use your code in my product but I cant provice any changes back.
Because I'm going to split your project. 
Am I allowed to copy & paste your code and use it as mine or do you want to be called?

**Comment by kr5ch** [comment]
rkon-core uses the MIT license. You have to include the license in your project and credit me, even if you use just part of it.

**Comment by kdoteu** [comment]
I was to blind ... you already got a licence file ... Thanks for the fast reply.
