### ISSUE TITLE
How to fix MalformedPacketException

### ISSUE THREAD

**Issue by Ivanzar** [Kronos666/rkon-core#3]
Hi, i have this problem:

`02-05 21:32:46.861 25260-25724/ivanzar.servertools W/System.err: core.ex.MalformedPacketException: Cannot read the whole packet
02-05 21:32:46.861 25260-25724/ivanzar.servertools W/System.err:     at core.RconPacket.read(RconPacket.java:136)
02-05 21:32:46.861 25260-25724/ivanzar.servertools W/System.err:     at core.RconPacket.send(RconPacket.java:65)
02-05 21:32:46.862 25260-25724/ivanzar.servertools W/System.err:     at core.Rcon.send(Rcon.java:106)
02-05 21:32:46.862 25260-25724/ivanzar.servertools W/System.err:     at core.Rcon.command(Rcon.java:99)
02-05 21:32:46.862 25260-25724/ivanzar.servertools W/System.err:     at ivanzar.servertools.activity.ConsoleActivity$2.doInBackground(ConsoleActivity.java:150)
02-05 21:32:46.862 25260-25724/ivanzar.servertools W/System.err:     at ivanzar.servertools.activity.ConsoleActivity$2.doInBackground(ConsoleActivity.java:135)
02-05 21:32:46.862 25260-25724/ivanzar.servertools W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
02-05 21:32:46.862 25260-25724/ivanzar.servertools W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-05 21:32:46.863 25260-25724/ivanzar.servertools W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
02-05 21:32:46.863 25260-25724/ivanzar.servertools W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-05 21:32:46.863 25260-25724/ivanzar.servertools W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-05 21:32:46.864 25260-25724/ivanzar.servertools W/System.err:     at java.lang.Thread.run(Thread.java:818)
`

**Comment by kr5ch** [comment]
_MalformedPacketException: Cannot read the whole packet_ means that the response you got from the Rcon server was malformed. What type of server were you connecting to ?

**Comment by Ivanzar** [comment]
What you mean ?

**Comment by Ivanzar** [comment]
I use via command method

**Comment by Ivanzar** [comment]
I use Nukkit server software and I get this error while I am sending "help"

**Comment by Ivanzar** [comment]
I see the messgae "Cannot read the whole packet"

**Comment by Ivanzar** [comment]
So, what do you think?

**Comment by kr5ch** [comment]
I've made some changes in the code, the new version (1.1.1) will handle big packets better. Next time please don't spam the issues and provide more info on your problem (like a log of your server while the problem occured).

**Comment by Ivanzar** [comment]
Ok, Thanks.
