### ISSUE TITLE
Code stops working mid process without errors.

### ISSUE THREAD

**Issue by ghost** [Kronos666/rkon-core#8]
Hello. Today I was trying to implement your code to my application and the code didn't work and it didn't throw any errors as well. I tried to track down the exact spot where the code stopped working and found out that in file **RconPocket.java** at line **113** it just stops and does nothing. I tried to fix it myself but couldn't really do it.

**Comment by hteppl** [comment]
+1

**Comment by kr5ch** [comment]
I am archiving this project, you are of course free to make forks according to the license.
